- name: Check arguments
  delegate_to: localhost
  fail: msg="{{ item }} is not defined"
  when: '{{ item }} is undefined'
  with_items:
    - name
    - arch
    - bridge
    - cpus
    - engine
    - memory
    - config_drive_disk_path
    - disk_path
  tags: [config-check]

- name: define vm
  delegate_to: localhost
  virt: name=test
        command=define
        xml="{{ lookup('template', 'vm.xml') }}"
