- name: Check arguments
  delegate_to: localhost
  fail: msg="{{ item }} is not defined"
  when: '{{ item }} is undefined'
  with_items:
    - name
    - arch
    - devnodes.cpus
    - engine
    - devnodes.memory
    - disk_path
  tags: [config-check]

- name: define vm
  delegate_to: localhost
  virt: name=test
        command=define
        xml="{{ lookup('template', 'vm.xml') }}"
